/* 
 * Script Runtime Service for vSphere
 *
 * # Script Runtime Service API    Script Runtime Service for vSphere (SRS) allows running PowerShell and PowerCLI scripts. SRS is a VC add-on that is deployed separately from VCSA. SRS can be accessed via REST API that allows you to create PowerShell instances and run PowerShell and PowerCLI scripts within. No Connect-VIServer is required to run PowerCLI against VC(s) SRS is registered to.    ## Authetication    SRS uses VC SSO as Identity and Authentication Server. Two types of authentication are supported. SIGN and Basic. SIGN authentication is purposed for Service-To-Service access to SRS resources. For convenience of the end-users SRS supports basic authentication passing username and password which are used to acquire SAML HoK token for SRS solution. When basic is used SRS exchanges the username and password for SAML HoK token from the SSO server. SRS uses the SAML token to Connect PowerCLI to VC services in further operations.   On successful authentication SRS returns API Key which is required to authorize further SRS API calls.
 *
 * OpenAPI spec version: 1.0-oas3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PlaceholderValue object represents single value for a placeholder in template script.
    /// </summary>
    [DataContract]
        public partial class PlaceholderValue :  IEquatable<PlaceholderValue>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlaceholderValue" /> class.
        /// </summary>
        /// <param name="placeholderName">Name of the placeholder in the script template which will be replaced on creation of an argument script. (required).</param>
        /// <param name="value">Value that will be used to replace the placeholder on creation of an argument script. (required).</param>
        public PlaceholderValue(string placeholderName = default(string), List<string> value = default(List<string>))
        {
            // to ensure "placeholderName" is required (not null)
            if (placeholderName == null)
            {
                throw new InvalidDataException("placeholderName is a required property for PlaceholderValue and cannot be null");
            }
            else
            {
                this.PlaceholderName = placeholderName;
            }
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new InvalidDataException("value is a required property for PlaceholderValue and cannot be null");
            }
            else
            {
                this.Value = value;
            }
        }
        
        /// <summary>
        /// Name of the placeholder in the script template which will be replaced on creation of an argument script.
        /// </summary>
        /// <value>Name of the placeholder in the script template which will be replaced on creation of an argument script.</value>
        [DataMember(Name="placeholder_name", EmitDefaultValue=false)]
        public string PlaceholderName { get; set; }

        /// <summary>
        /// Value that will be used to replace the placeholder on creation of an argument script.
        /// </summary>
        /// <value>Value that will be used to replace the placeholder on creation of an argument script.</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public List<string> Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PlaceholderValue {\n");
            sb.Append("  PlaceholderName: ").Append(PlaceholderName).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PlaceholderValue);
        }

        /// <summary>
        /// Returns true if PlaceholderValue instances are equal
        /// </summary>
        /// <param name="input">Instance of PlaceholderValue to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PlaceholderValue input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PlaceholderName == input.PlaceholderName ||
                    (this.PlaceholderName != null &&
                    this.PlaceholderName.Equals(input.PlaceholderName))
                ) && 
                (
                    this.Value == input.Value ||
                    this.Value != null &&
                    input.Value != null &&
                    this.Value.SequenceEqual(input.Value)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PlaceholderName != null)
                    hashCode = hashCode * 59 + this.PlaceholderName.GetHashCode();
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
