apiVersion: v1
kind: Namespace
metadata:
  name: script-runtime-service
  labels:
    app.kubernetes.io/name: script-runtime-service
    app.kubernetes.io/instance: script-runtime-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-settings
  namespace: script-runtime-service
data:
  settings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Trace",
          "Microsoft": "Information"
        }
      },
      "AllowedHosts": "*",
      "RunspaceProviderSettings": {
        "K8sRunspaceImageName": "pclirunspace:latest",
        "K8sRunspacePort": 5550,
        "K8sVerifyRunspaceApiIsAccessibleOnCreate": true,
        "RunspaceTrustedCertsConfigMapName": "trusted-ca-certs",
        "MaxNumberOfRunspaces": 5,
        "MaxRunspaceIdleTimeMinutes": 10,
        "MaxRunspaceActiveTimeMinutes": 60
      },
      "ScriptExecutionStorageSettings": {
        "ServiceScriptStorageDir": "/app/service/scriptsstore",
        "NumberOfScriptsPerUser": 30,
        "NoOlderThanDays": 5
      }
    }
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: srs-admin
  namespace: script-runtime-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: srs-setup
  namespace: script-runtime-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-configs
  namespace: script-runtime-service
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-srs-setup
  namespace: script-runtime-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-configs
subjects:
- kind: ServiceAccount
  name: srs-setup
- kind: ServiceAccount
  name: srs-admin
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: srs-setup
  name: srs-setup
  namespace: script-runtime-service
spec:
  template:
    spec:
      serviceAccountName: srs-setup
      containers:
      - image: "srs-setup:1.0"
        name: srs-setup
        imagePullPolicy: IfNotPresent
        command: ["/app/service/setup"]
        env:
          - name: TARGET_VC_SERVER
            value: "${VC_SERVER}"
          - name: TARGET_VC_USER
            value: "${VC_USER}"
          - name: TARGET_VC_PASSWORD
            value: "${VC_PASSWORD}"
          - name: TARGET_VC_THUMBPRINT
            value: ${VC_THUMBPRINT}
          - name: TARGET_VC_CLEAN
            value: "${VC_CLEAN}"
          - name: SERVICE_HOSTNAME
            value: "${SRSA_HOSTNAME}"
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: srs-runspace-provider
  namespace: script-runtime-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-pods
  namespace: script-runtime-service
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "configmaps", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-pods_srs-runspace-provider
  namespace: script-runtime-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-pods
subjects:
- kind: ServiceAccount
  name: srs-runspace-provider
  namespace: script-runtime-service
- kind: ServiceAccount
  name: srs-admin
  namespace: script-runtime-service
---
apiVersion: v1
kind: Secret
metadata:
  name: srs-adminapi-credentials
  namespace: script-runtime-service
type: Opaque
data:
  ADMIN_USER: "${ADMIN_USER}"
  ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
  ADMIN_PASSWORD_SALT: "${ADMIN_PASSWORD_SALT}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: srs-adminapi
  name: srs-adminapi
  namespace: script-runtime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs-adminapi
  template:
    metadata:
      labels:
        app: srs-adminapi
    spec:
      serviceAccountName: srs-admin
      containers:
        - image: "srs-adminapi:1.0"
          imagePullPolicy: IfNotPresent
          name: srs-adminapi
          volumeMounts:
            - name: service-settings
              mountPath: "/app/service/settings/settings"
              readOnly: false
            - name: sts-settings
              mountPath: "/app/service/settings/sts-settings"
              readOnly: false
            - name: trusted-ca-certs
              mountPath: "/app/service/trusted-ca-certs"
              readOnly: false
            - name: sign-certificate
              mountPath: "/app/service/settings/sign-certs"
              readOnly: false
            - name: tls-certificate
              mountPath: "/app/service/settings/tls-certs"
              readOnly: false
          ports:
            - containerPort: 5555
              protocol: TCP
          env:
            - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
              value: "1"
            - name: SERVICE_SIGNING_CERTIFICATE_PATH
              value: "/app/service/settings/sign-certs/srs-sign.p12"
            - name: SERVICE_TLS_CERTIFICATE_PATH
              value: "/app/service/settings/tls-certs/tls.crt"
            - name: SERVICE_HOSTNAME
              value: "${SRSA_HOSTNAME}"
          envFrom:
            - secretRef:
                name: srs-adminapi-credentials
                optional: true
      volumes:
        - name: sign-certificate
          secret:
            secretName: srs-sign
            optional: true
        - name: tls-certificate
          secret:
            secretName: srs-tls
            optional: true
        - name: trusted-ca-certs
          configMap:
            name: trusted-ca-certs
            optional: true
        - name: service-settings
          configMap:
            name: service-settings
            optional: true
            items:
            - key: settings.json
              path: settings.json
        - name: sts-settings
          configMap:
            name: sts-settings
            optional: true
            items:
            - key: sts-settings.json
              path: sts-settings.json
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: srs-apigateway
  name: srs-apigateway
  namespace: script-runtime-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srs-apigateway
  template:
    metadata:
      labels:
        app: srs-apigateway
    spec:
      serviceAccountName: srs-runspace-provider
      containers:
        - image: "srs-apigateway:1.0"
          imagePullPolicy: IfNotPresent
          name: srs-apigateway
          volumeMounts:
            - name: service-settings
              mountPath: "/app/service/settings/settings"
              readOnly: true
            - name: sts-settings
              mountPath: "/app/service/settings/sts-settings"
              readOnly: true
            - name: trusted-ca-certs
              mountPath: "/app/service/trusted-ca-certs"
              readOnly: true
            - name: sign-certificate
              mountPath: "/app/service/settings/certs"
              readOnly: true
          ports:
            - containerPort: 5050
              protocol: TCP
          env:
            - name: SERVICE_SETTINGS_LOCATION
              value: "/app/service/settings/settings/settings.json"
            - name: SERVICE_STS_SETTINGS_LOCATION
              value: "/app/service/settings/sts-settings/sts-settings.json"
      volumes:
        - name: sign-certificate
          secret:
            secretName: srs-sign
        - name: trusted-ca-certs
          configMap:
            name: trusted-ca-certs
        - name: service-settings
          configMap:
            name: service-settings
            items:
            - key: settings.json
              path: settings.json
        - name: sts-settings
          configMap:
            name: sts-settings
            items:
            - key: sts-settings.json
              path: sts-settings.json
---
apiVersion: v1
kind: Service
metadata:
  name: srs-adminapi
  namespace: script-runtime-service
spec:
  ports:
  - port: 5555
    protocol: TCP
    targetPort: 5555
  selector:
    app: srs-adminapi
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: srs-apigateway
  namespace: script-runtime-service
spec:
  ports:
  - port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: srs-apigateway
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: srs-ingress
  namespace: script-runtime-service
spec:
  tls:
  - hosts:
    - ${SRSA_HOSTNAME}
    secretName: srs-tls
  rules:
  - host: ${SRSA_HOSTNAME}
  - http:
      paths:
      - path: /(swagger/admin.*)
        pathType: Prefix
        backend:
          serviceName: srs-adminapi
          servicePort: 5555
      - path: /admin/(swagger.*)
        pathType: Prefix
        backend:
          serviceName: srs-adminapi
          servicePort: 5555
      - path: /(admin/.*)
        pathType: Prefix
        backend:
          serviceName: srs-adminapi
          servicePort: 5555
      - path: /(swagger/srs.*)
        pathType: Prefix
        backend:
          serviceName: srs-apigateway
          servicePort: 5050
      - path: /api/(swagger.*)
        pathType: Prefix
        backend:
          serviceName: srs-apigateway
          servicePort: 5050
      - path: /(api/.*)
        pathType: Prefix
        backend:
          serviceName: srs-apigateway
          servicePort: 5050
