//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VMware.ScriptRuntimeService.DockerRunspaceProvider.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VMware.ScriptRuntimeService.DockerRunspaceProvider.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No IP Address was assigned for the Runspace Container. It was either not attached to the &apos;{0}&apos; docker network or docker engine failed to assign IP Address..
        /// </summary>
        internal static string DockerRunspaceInfo_DockerRunspaceInfo_InvalidIp {
            get {
                return ResourceManager.GetString("DockerRunspaceInfo_DockerRunspaceInfo_InvalidIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TCP Port in containerInspectResponse.NetworkSettings.Ports.
        /// </summary>
        internal static string DockerRunspaceInfo_DockerRunspaceInfo_NoTcpPort {
            get {
                return ResourceManager.GetString("DockerRunspaceInfo_DockerRunspaceInfo_NoTcpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get RunspaceInfo because ContainerInspectResponse is null.
        /// </summary>
        internal static string DockerRunspaceInfo_FromContainerInspectResponse_ContainerInspectResponse_IsNull {
            get {
                return ResourceManager.GetString("DockerRunspaceInfo_FromContainerInspectResponse_ContainerInspectResponse_IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create DockerRunspaceInfo from ContainerInspectResponse {0}.
        /// </summary>
        internal static string DockerRunspaceProvider_Create_DockerRunspaceInfoCreateFail {
            get {
                return ResourceManager.GetString("DockerRunspaceProvider_Create_DockerRunspaceInfoCreateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container has been created but it is not accessible over the network.
        /// </summary>
        internal static string DockerRunspaceProvider_Create_NewContainerIsNotAccessible {
            get {
                return ResourceManager.GetString("DockerRunspaceProvider_Create_NewContainerIsNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker Engine ContainerCreate API failed.
        /// </summary>
        internal static string DockerRunspaceProvider_Create_StartContainerDockerAPIFail {
            get {
                return ResourceManager.GetString("DockerRunspaceProvider_Create_StartContainerDockerAPIFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Invalid Docker Engine Endpoit Uri &apos;{0}&apos;&quot;.
        /// </summary>
        internal static string DockerRunspaceProvider_DockerRunspaceProvider_InvalidDockerEndpointUrl {
            get {
                return ResourceManager.GetString("DockerRunspaceProvider_DockerRunspaceProvider_InvalidDockerEndpointUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker Engine ContainerGet API failed.
        /// </summary>
        internal static string DockerRunspaceProvider_Get_ContainerDockerAPIFail {
            get {
                return ResourceManager.GetString("DockerRunspaceProvider_Get_ContainerDockerAPIFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docker Engine ContainerKill operation failed.
        /// </summary>
        internal static string DockerRunspaceProvider_Kill_KillContainerDockerAPIFail {
            get {
                return ResourceManager.GetString("DockerRunspaceProvider_Kill_KillContainerDockerAPIFail", resourceCulture);
            }
        }
    }
}
