/* 
 * Runspace API V1
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using System;
using RestSharp;

namespace VMware.ScriptRuntimeService.RunspaceClient.Bindings.Client {
   /// <summary>
   /// A delegate to ExceptionFactory method
   /// </summary>
   /// <param name="methodName">Method name</param>
   /// <param name="response">Response</param>
   /// <returns>Exceptions</returns>
   public delegate Exception ExceptionFactory(string methodName, IRestResponse response);
}
