openapi: 3.0.1
info:
  title: Script Runtime Service
  description: Script Runtime Service Admin API
  contact:
    name: Script Runtime Service for vSphere
    url: https://github.com/vmware/script-runtime-service-for-vsphere
  version: 1.0.0
paths:
  /admin/logs:
    get:
      tags:
        - Log
      operationId: get-log
      parameters:
        - name: type
          in: query
          schema:
            $ref: '#/components/schemas/LogType'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
  /admin/vc-registration:
    post:
      tags:
        - VCenterRegistration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VCInfo'
      responses:
        '200':
          description: Success
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
    get:
      tags:
        - VCenterRegistration
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisteredVC'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
    delete:
      tags:
        - VCenterRegistration
      parameters:
        - name: clean
          in: query
          schema:
            type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VCInfo'
      responses:
        '200':
          description: Success
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
components:
  schemas:
    LogType:
      enum:
        - 0
        - 1
        - 2
      type: integer
      format: int32
    ErrorDetails:
      type: object
      properties:
        code:
          type: integer
          format: int32
        error_message:
          type: string
          nullable: true
        details:
          type: string
          nullable: true
      additionalProperties: false
    VCInfo:
      type: object
      properties:
        address:
          type: string
          nullable: true
        thumbprint:
          type: string
          nullable: true
        username:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
      additionalProperties: false
    RegisteredVC:
      type: object
      properties:
        vc_address:
          type: string
          nullable: true
      additionalProperties: false